Revert "platform: qpnp-power-on: Add support for TWM config"
This reverts commit 236905aed640dbe45502f5a9dfc5b4c21e2f3ee2.

drivers/platform/msm/qpnp-power-on.c: In function 'qpnp_pon_probe':
drivers/platform/msm/qpnp-power-on.c:2378:3: error: implicit declaration of function 'pon_register_twm_notifier' [-Werror=implicit-function-declaration]
   rc = pon_register_twm_notifier(pon);
   ^
cc1: some warnings being treated as errors
make[3]: *** [drivers/platform/msm/qpnp-power-on.o] Error 1